#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
modelBuoy_collocation.py

VERSION AND LAST UPDATE:
 v1.0  05/11/2022
 v1.1  05/18/2022
 v1.2  06/30/2022
 v1.3  11/17/2022
 v1.4  12/08/2022
 v1.5  01/31/2023
 v1.6  05/21/2024

PURPOSE:
 Collocation/pairing ww3 point output results with wave buoys.
 Matchups of ww3 results and buoy data are generated for the same
  points (lat/lon) and time.
 Additional information can be collocated as well, such as water depth,
  distance to the nearest coast, ocean names, forecast zones, and 
  cyclone information.
 This code is designed for ww3 hindcasts or forecast with 
  consecutive cycles (overlapped time). The ww3 file(s) are not inserted
  directly but it is informed through a list, ww3list.txt (or any other
  name), that is read as an argument. Multiple file names can be writen 
  in the list, ww3 results will be appended, depending on the data 
  structure selected (hindcast or forecast). The default is hindcast, so 
  arrays are directly appended in time. By entering a second argument 
  (any value greater than zero), the program assumes it is a forecast data 
  structure, i.e., the list contains consecutive cycles (each file is 
  one cycle) interpreted as another dimension (cycle time and 
  forecast lead time).

USAGE:
 Input WW3 point outputs are utilized (not grids), with option of
modelBuoy_collocation.py  reading different formats: netcdf, text (bull and ts), 
  or tar files with multiple bull or ts files.
 For the observations, it uses two public buoy databases, 
  NDBC and Copernicus, which (at least one) must have been previously 
  downloaded. See wfetchbuoy.py at ww3tools/downloadobs
 Users must edit ndbcp and copernp paths below.
 Python code can be run directly. At least one argument is needed, with
  the list name of point output ww3 files (or one single file). This list
  can be written, for example: ls -d -1 $PWD/ww3.*.nc >> ww3list.txt
 The second argument (optional) is an integer with any value greater than
  zero for the program to assume it is a forecast data structure.
 In addition to ww3list.txt and forecast data-shape, users can enter 
  two extra arguments, gridInfo and CycloneMap, generated by 
  prepGridMask.py and procyclmap.py, where the information of buoy's
  position (nearest grid point) will be extracted and included in the
  output netcdf file.
 Example (from linux terminal command line):
  multiple hindcast data files:
  nohup python3 modelBuoy_collocation.py ww3list.gfs-d36.GSE1.5.txt 0 gridInfo.nc CycloneMap_2021.nc >> nohup_modelBuoy_collocation.out 2>&1 &
  multiple forecast data files:
  nohup python3 modelBuoy_collocation.py ww3list.gfs-d36.GSE1.5.txt 2 gridInfo.nc CycloneMap_2021.nc >> nohup_modelBuoy_collocation.out 2>&1 &

- From 05/21/24 if you want to run this you have to define the (buoy_path) variable in the command line or in the job script. This recent does not accept the 
hard coded ndbcp path anymore.

USAGE (spec.gz):
 In wread.py the ww3_spec1 is responsible for reading and accepting the spec.gz files like,ex:gfswave.t00z.spec_tar.gz
 sort of files. 
 to run the code one should have to define these values in the job script or the command line: 

# Define the arguments
 input_gz_file="./gfswave.t00z.spec_tar.gz"
 output_directory="./"  (Where the users wants to have the output saved)
 buoy_path="/scratch2/NCEPDEV/marine/Matthew.Masarik/dat/buoys/NDBC/ncformat/wparam" (The path should be changed based on the users buoy path directory)
 model_name="HR3a"   # Define the model name
 forecast_ds="1"    # Indicator for forecast data structure, set to 1 or 0 based on requirements
 (If it is 1 or greater than 1, it does the forecast structure)

# Process data for each date
 python3 modelBuoy_collocation.py spec.gz "$input_gz_file" "$output_directory" "$buoy_path"  "$model_name " "$forecast_ds"


Note: Updated way for submitting formats(bulltar) other than spec.gz:


buoy_path="/scratch2/NCEPDEV/marine/Matthew.Masarik/dat/buoys/NDBC/ncformat/wparam"
The buoy path should be defined in the job script.

# Process data for each date
python3 modelBuoy_collocation.py ww3list.txt(any text file name that user defined)  2 $buoy_path
(The buoy path should be the last item)


OUTPUT:
 netcdf file WW3.Buoy*.nc containing matchups of buoy and ww3 data,
  for the stations (lat/lon) where both data sources are available.
 for the examples above, the program will select the tag gfs-d36.GSE1.5 to
  name the output file as WW3.Buoy.gfs-d36.GSE1.5_2021092400to2021102400.nc
  containing WW3.Buoy, the tag to identify the simulation, and start
  and final date.

DEPENDENCIES:
 See setup.py and the imports below.
 ww3 point output results (list of files ww3list.txt)
 NDBC buoy data (see wfetchbuoy.py)
 Copernicus buoy data (see wfetchbuoy.py)

AUTHOR and DATE:
 05/11/2022: Ricardo M. Campos, first version.
 05/18/2022: Ricardo M. Campos, inclusion of gridInfo mask information,
  with water depth, distance to coast, ocean names, forecast areas, and
  cyclone information.
 06/30/2022: Ricardo M. Campos, including option of using a forecast
  data structure, where each file name in the ww3list is taken as a
  forecast cycle.
 11/17/2022: Ricardo M. Campos, another point output ww3 format (bull)
  included. New variables, peak period (Tp) and peak direction (Dp)
  added.
 12/08/2022: Ricardo M. Campos, point output ww3 format (bull_tar) and .ts
  included. Allow forecast array dimension (cycle-time and lead-time) for
  bull_tar
 01/31/2023: Ricardo M. Campos, fix reshape array for forecast data (two time
  dimensions), and check if variable names exist in the netcdf file (buoy 
  and ww3) to maximize the amount of matchups even when one variable is 
  not available.
 05/21/2024 : Ghazal Mohammadpour , developed the code to be able to process 
 the spec.gz files.


PERSON OF CONTACT:
 Ricardo M Campos: ricardo.campos@noaa.gov

"""

import sys
import os
import gzip
import tarfile
import warnings
import numpy as np
import netCDF4 as nc
import time
from time import strptime
from calendar import timegm
import wread
import glob
import shutil

# Suppressing warnings
warnings.filterwarnings("ignore")

# netCDF format specification
fnetcdf = "NETCDF4"

gridinfo = None
cyclonemap = None
wlist = []
ftag = ''

# Function to unzip and untar files
def unzip_and_untar(gz_file, output_dir):
    try:
        file_name = os.path.splitext(os.path.basename(gz_file))[0]
        base_name = file_name.rsplit('.', 1)[0]
        output_file = os.path.join(output_dir, file_name)

        with gzip.open(gz_file, 'rb') as f_in:
            with open(output_file, 'wb') as f_out:
                f_out.write(f_in.read())

        extracted_folder = os.path.join(output_dir, base_name)

        with tarfile.open(output_file, 'r') as tar:
            tar.extractall(extracted_folder)

        # Creating a list of the extracted files
        list_file = os.path.join(output_dir, f'{base_name}_contents.txt')
        with open(list_file, 'w') as f:
            for root, dirs, files in os.walk(extracted_folder):
                for file in files:
                    f.write(os.path.join(root, file) + '\n')

        # Creating a list of ids between two dots in the filenames
        id_file = os.path.join(output_dir, f'{base_name}_id.txt')
        with open(id_file, 'w') as f:
            for root, dirs, files in os.walk(extracted_folder):
                for file in files:
                    file_parts = file.split('.')
                    if len(file_parts) >= 3:
                        id_between_dots = file_parts[1]
                        f.write(id_between_dots + '\n')

        # Return the path to the extracted folder
        return extracted_folder, list_file, id_file
    except Exception as e:
        print(f"Error in unzip_and_untar: {e}")
        sys.exit(1)

# Main part of the script
if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else ""

    if mode == "spec.gz":
        if len(sys.argv) != 7:
            sys.exit("Usage: python script.py spec.gz input_gz_file output_directory buoy_path model_name forecastds")

        gz_file = sys.argv[2]
        output_dir = sys.argv[3]
        buoy_path = sys.argv[4]
        model_name = sys.argv[5]
        forecastds = int(sys.argv[6])  # Convert forecast indicator to integer

        # Debugging lines
        print(f"gz_file: {gz_file}")
        print(f"output_dir: {output_dir}")
        print(f"buoy_path: {buoy_path}")
        print(f"model_name: {model_name}")
        print(f"forecastds: {forecastds}")

        print(f"Unzipping and untarring {gz_file} to {output_dir}")
        ndbcp = buoy_path
        extracted_folder, list_file, id_file = unzip_and_untar(gz_file, output_dir)

        print("Extraction completed. Extracted files are in:", extracted_folder)
        print("Contents list file:", list_file)
        print("ID list file:", id_file)

        # Read file names from the extracted folder
        file_names = []
        for root, dirs, files in os.walk(extracted_folder):
            for file in files:
                file_names.append(os.path.join(root, file))

        if not file_names:
            print("No files found in the extracted folder.")
            sys.exit(1)

        print("List of files to process:", file_names)

        # Read id_files (if needed)
        id_files = []
        with open(id_file, 'r') as f:
            for line in f:
                id_files.append(line.strip())

        if not id_files:
            print("No IDs found in the ID list file.")
            sys.exit(1)

        print("List of IDs:", id_files)

        # Call the spec_ww3 function with the file names and ID files
        try:
            print("Calling wread.spec1_ww3...")
            results =wread. spec1_ww3(file_names, id_files)
            print("wread.spec1_ww3 call completed.")
        except Exception as e:
            print(f"Error in wread.spec1_ww3: {e}")
            sys.exit(1)

        # Additional processing (if needed)
        mfcycle = None
        stname = None
        mtime = None
        mhs = None
        mtp = None
        mwn = None
        mwd = None
        mfreq = None
        mtm = None
        mdm = None
        mdp = None

        try:
            for i, result in enumerate(results):
                print(f"Processing result {i+1}/{len(results)}...")
                at = result['time']

                if i == 0:
                    mfcycle = np.array(np.zeros((at.shape[0]), 'd') + at[0]).astype('double')
                    stname = np.atleast_1d(np.array(result['station_name']))
                    mtime = np.copy(at)
                    mhs = np.copy([result['Hs']])
                    mtp = np.copy([result['Tp']])

                    if 'wind_spd' in result.keys():
                        mwn = np.copy([result['wind_spd']])
                    else:
                        mwn = np.copy(mhs) * np.nan

                    if 'wind_dir' in result.keys():
                        mwd = np.copy([result['wind_dir']])
                    else:
                        mwd = np.copy(mhs) * np.nan

                    if 'freq' in result.keys():
                        mfreq = np.copy([result['freq']])
                    else:
                        mfreq = np.copy(mhs) * np.nan

                    if 'tm' in result.keys():
                        mtm = np.copy([result['tm']])
                    else:
                        mtm = np.copy(mhs) * np.nan

                    if 'dp' in result.keys():
                        mdp = np.copy([result['dp']])
                    else:
                        mdp = np.copy(mhs) * np.nan

                    if 'dm' in result.keys():
                        mdm = np.copy([result['dm']])
                    else:
                        mdm = np.copy(mhs) * np.nan

                else:
                    if mhs.shape[1] == result['Hs'].shape[0]:
                        stname = np.append(stname, np.atleast_1d(np.array(result['station_name'])))
                        mhs = np.append(mhs, [result['Hs']], axis=0)
                        mtp = np.append(mtp, [result['Tp']], axis=0)

                        if 'wind_spd' in result.keys():
                            mwn = np.append(mwn, [result['wind_spd']], axis=0)
                        else:
                            mwn = np.append(mwn, [np.copy(result['Hs']) * np.nan], axis=0)

                        if 'wind_dir' in result.keys():
                            mwd = np.append(mwd, [result['wind_dir']], axis=0)
                        else:
                            mwd = np.append(mwd, [np.copy(result['Hs']) * np.nan], axis=0)

                        if 'freq' in result.keys():
                            mfreq = np.append(mfreq, [result['freq']], axis=0)
                        else:
                            mfreq = np.append(mfreq, [np.copy(result['Hs']) * np.nan], axis=0)

                        if 'tm' in result.keys():
                            mtm = np.append(mtm, [result['tm']], axis=0)
                        else:
                            mtm = np.append(mtm, [np.copy(result['Hs']) * np.nan], axis=0)

                        if 'dp' in result.keys():
                            mdp = np.append(mdp, [result['dp']], axis=0)
                        else:
                            mdp = np.append(mdp, [np.copy(result['Hs']) * np.nan], axis=0)

                        if 'dm' in result.keys():
                            mdm = np.append(mdp, [result['dm']], axis=0)
                        else:
                            mdm = np.append(mdm, [np.copy(result['Hs']) * np.nan], axis=0)

                    else:
                        print("   Stations in file do not match the other tar files. Skipped")

            print("Completed processing results.")

            # Add additional debugging statements here
            print("Checking final data structures...")
            print(f"mfcycle: {mfcycle}")
            print(f"stname: {stname}")
            print(f"mtime: {mtime}")
            print(f"mhs: {mhs}")
            print(f"mtp: {mtp}")
            print(f"mwn: {mwn}")
            print(f"mwd: {mwd}")
            print(f"mfreq: {mfreq}")
            print(f"mtm: {mtm}")
            print(f"mdm: {mdm}")
            print(f"mdp: {mdp}")

        except Exception as e:
            print(f"Error during processing: {e}")
            sys.exit(1)


    else:
        wlist = []
        ftag = ''
        forecastds = 0

        if len(sys.argv) < 3:
            sys.exit('At least one argument (list of ww3 files) must be informed.')
        wlist = np.atleast_1d(np.loadtxt(sys.argv[1], dtype=str))
        ftag = str(sys.argv[1]).split('list')[1].split('.txt')[0]
        print('Reading ww3 list ' + str(sys.argv[1]))
        print('Tag ' + ftag)

        forecastds = int(sys.argv[2]) if len(sys.argv) >= 4 else 0
        if forecastds > 0:
            print('Forecast-type data structure')

        # Determine if gridinfo and cyclonemap are provided
        if len(sys.argv) >= 6:
            ndbcp = sys.argv[3]
            gridinfo = sys.argv[4]
            cyclonemap = sys.argv[5]
            print('Using ndbcp path:', ndbcp)
            print('Using gridinfo:', gridinfo)
            print('Using cyclonemap:', cyclonemap)
        else:
            # If gridinfo and cyclonemap are not both provided, use the last argument as buoy_path
            buoy_path = sys.argv[-1]
            ndbcp = buoy_path
            # Check if gridinfo is provided without cyclonemap or vice versa
            if 'gridinfo' in sys.argv:
                gridinfo = sys.argv[3]
                print('Using gridinfo:', gridinfo)

            if 'cyclonemap' in sys.argv:
                cyclonemap = sys.argv[3]
                print('Using cyclonemap:', cyclonemap)

            print('Using ndbcp path:', buoy_path)

        # READ DATA
        print(" ")
        if gridinfo:
            # Grid Information
            gridmask = wread.mask(gridinfo)
            mlat = gridmask['latitude']
            mlon = gridmask['longitude']
            mask = gridmask['mask']
            distcoast = gridmask['distcoast']
            depth = gridmask['depth']
            oni = gridmask['GlobalOceansSeas']
            ocnames = gridmask['names_GlobalOceansSeas']
            hsmz = gridmask['HighSeasMarineZones']
            hsmznames = gridmask['names_HighSeasMarineZones']
            print("  GridInfo Ok. " + gridinfo)

            # Cyclone Information
            if cyclonemap:
                cycloneinfo = wread.cyclonemap(cyclonemap)
                clat = cycloneinfo['latitude']
                clon = cycloneinfo['longitude']
                cmap = cycloneinfo['cmap']
                ctime = cycloneinfo['time']
                cinfo = np.array(cycloneinfo['info'].split(':')[1].split(';'))
                if np.array_equal(clat, mlat) & np.array_equal(clon, mlon):
                    print("  CycloneMap Ok. " + cyclonemap)
                else:
                    sys.exit(' Error: Cyclone grid and Mask grid are different.')

        # MODEL Point output, search among possible formats
        if (str(wlist[0]).split('/')[-1].split('.')[-1] == 'bull_tar') or (
                str(wlist[0]).split('/')[-1].split('.')[-1] == 'station_tar'):
            for i in range(0, np.size(wlist)):
                if str(wlist[i]).split('/')[-1].split('.')[-1] == 'bull_tar':
                    result = wread.bull_tar(wlist[i])
                if str(wlist[i]).split('/')[-1].split('.')[-1] == 'station_tar':
                    result = wread.bull_tar(wlist[i])

                at = result['time']
                fcycle = np.array(np.zeros((at.shape[0]), 'd') + at[0]).astype('double')
                if i == 0:
                    stname = result['station_name']
                    mtime = np.copy(at)
                    mfcycle = np.copy(fcycle)
                    mhs = np.copy(result['hs'])
                    mtp = np.copy(result['tp'])
                    if 'dp' in result.keys():
                        mdp = np.copy(result['dp'])
                    else:
                        mdp = np.copy(mhs) * np.nan

                    if 'wind_spd' in result.keys():
                        mwn = np.copy(result['wind_spd'])
                    else:
                        mwn = np.copy(mhs) * np.nan

                    if 'wind_dir' in result.keys():
                        mwd = np.copy(result['wind_dir'])
                    else:
                        mwd = np.copy(mhs) * np.nan

                else:
                    if (mhs.shape[0] == result['hs'].shape[0]) and (
                            np.size(stname) == np.size(result['station_name'])):
                        if (stname == result['station_name']).all():
                            mtime = np.append(mtime, at)
                            mfcycle = np.append(mfcycle, fcycle)
                            mhs = np.append(mhs, result['hs'], axis=1)
                            mtp = np.append(mtp, result['tp'], axis=1)
                            if 'dp' in result.keys():
                                mdp = np.append(mdp, result['dp'], axis=1)
                            else:
                                mdp = np.append(mdp, np.copy(result['hs']) * np.nan, axis=1)

                            if 'wind_spd' in result.keys():
                                mwn = np.append(mwn, result['wind_spd'], axis=1)
                            else:
                                mwn = np.append(mwn, np.copy(result['hs']) * np.nan, axis=1)

                            if 'wind_dir' in result.keys():
                                mwd = np.append(mwd, result['wind_dir'], axis=1)
                            else:
                                mwd = np.append(mwd, np.copy(result['hs']) * np.nan, axis=1)

                    else:
                        print("   Stations in " + wlist[i] + " do not match the other tar files. Skipped " + wlist[i])

                del result, at, fcycle
                mdm = np.copy(mhs) * np.nan
                mtm = np.copy(mhs) * np.nan
                print("    ww3 file " + wlist[i] + " OK")

        elif (str(wlist[0]).split('/')[-1].split('.')[-1] == 'bull') or (
                str(wlist[0]).split('/')[-1].split('.')[-1] == 'ts'):
            if forecastds > 0:
                forecastds = 0  # no 2D time array possible.
                print(
                    "  Warning: no 2D time array possible. Use multiple tar files (one per forecast cycle), station_tar or bull_tar, containing text files for each station.")

            for i in range(0, np.size(wlist)):
                # re-check each file in the list respects the same format
                if str(wlist[i]).split('/')[-1].split('.')[-1] == 'ts':
                    result = wread.ts(wlist[i])
                elif str(wlist[i]).split('/')[-1].split('.')[-1] == 'bull':
                    result = wread.bull(wlist[i])

                at = result['time']
                if i == 0:
                    mfcycle = np.array(np.zeros((at.shape[0]), 'd') + at[0]).astype('double')
                    stname = np.atleast_1d(np.array(result['station_name']))
                    mtime = np.copy(at)
                    mhs = np.copy([result['hs']])
                    mtp = np.copy([result['tp']])
                    if 'dp' in result.keys():
                        mdp = np.copy([result['dp']])
                    else:
                        mdp = np.copy(mhs) * np.nan

                    if 'dm' in result.keys():
                        mdm = np.copy([result['dm']])
                    else:
                        mdm = np.copy(mhs) * np.nan

                    if 'tm' in result.keys():
                        mtm = np.copy([result['tm']])
                    else:
                        mtm = np.copy(mhs) * np.nan

                else:
                    if (mhs.shape[1] == result['hs'].shape[0]):
                        stname = np.append(stname, np.atleast_1d(np.array(result['station_name'])))
                        mtime = np.append(mtime, at)
                        mhs = np.append(mhs, [result['hs']], axis=0)
                        mtp = np.append(mtp, [result['tp']], axis=0)
                        if 'dp' in result.keys():
                            mdp = np.append(mdp, [result['dp']], axis=0)
                        else:
                            mdp = np.append(mdp, [np.copy(result['hs']) * np.nan], axis=0)

                        if 'dm' in result.keys():
                            mdm = np.append(mdp, [result['dm']], axis=0)
                        else:
                            mdm = np.append(mdm, [np.copy(result['hs']) * np.nan], axis=0)

                        if 'tm' in result.keys():
                            mtm = np.append(mtm, [result['tm']], axis=0)
                        else:
                            mtm = np.append(mtm, [np.copy(result['hs']) * np.nan], axis=0)

                    else:
                        print("   Stations in " + wlist[i] + " do not match the other tar files. Skipped " + wlist[i])

                del result, at
                print("    ww3 file " + wlist[i] + " OK")

        elif str(wlist[0]).split('/')[-1].split('.')[-1] == 'nc':
            print(" Using ww3 netcdf point output format")
            # netcdf point output file
            for t in range(0, np.size(wlist)):
                try:
                    f = nc.Dataset(str(wlist[t]))
                except:
                    print(" Cannot open " + wlist[t])
                else:
                    # list of station/buoy names
                    if t == 0:
                        auxstationname = f.variables['station_name'][:, :]
                        stname = []
                        for i in range(0, auxstationname.shape[0]):
                            astname = "".join(np.array(auxstationname[i, :]).astype('str'))
                            if '\t' in astname:
                                astname = str(astname).replace("\t", "")

                            stname = np.append(stname, astname)
                            del astname

                        funits = f.variables['time'].units
                        if str(funits).split(' ')[0] == 'seconds':
                            tincr = 1
                        elif str(funits).split(' ')[0] == 'hours':
                            tincr = 3600
                        elif str(funits).split(' ')[0] == 'days':
                            tincr = 24 * 3600

                    ahs = np.array(f.variables['hs'][:, :]).T

                    if 'th1m' in f.variables.keys():
                        adm = np.array(f.variables['th1m'][:, :]).T
                    else:
                        adm = np.array(np.copy(ahs * np.nan))

                    if 'th1p' in f.variables.keys():
                        adp = np.array(f.variables['th1p'][:, :]).T
                    else:
                        adp = np.array(np.copy(ahs * np.nan))

                    if 'tr' in f.variables.keys():
                        atm = np.array(f.variables['tr'][:, :]).T
                    else:
                        atm = np.array(np.copy(ahs * np.nan))

                    if 'fp' in f.variables.keys():
                        auxtp = np.array(f.variables['fp'][:, :]).T
                        indtp = np.where(auxtp > 0.)
                        if np.size(indtp) > 0:
                            atp = np.copy(auxtp)
                            atp[indtp] = np.copy(1. / atp[indtp])
                            del indtp

                        del auxtp

                    else:
                        atm = np.array(np.copy(ahs * np.nan))

                    ftunits = str(f.variables['time'].units).split('since')[1][1::].replace('T', ' ').replace('+00:00', '')
                    at = np.array(
                        f.variables['time'][:] * tincr + timegm(strptime(ftunits, '%Y-%m-%d %H:%M:%S'))).astype('double')

                    f.close()
                    del f
                    fcycle = np.array(np.zeros((at.shape[0]), 'd') + at[0]).astype('double')
                    if t == 0:
                        mhs = np.copy(ahs)
                        mtm = np.copy(atm)
                        mtp = np.copy(atp)
                        mdm = np.copy(adm)
                        mdp = np.copy(adp)
                        mwn = np.copy(awm)
                        mtime = np.copy(at)
                        mfcycle = np.copy(fcycle)
                    else:
                        mhs = np.append(mhs, ahs, axis=1)
                        mtm = np.append(mtm, atm, axis=1)
                        mtp = np.append(mtp, atp, axis=1)
                        mdm = np.append(mdm, adm, axis=1)
                        mdp = np.append(mdp, adp, axis=1)
                        mwn = np.append(mwn, awm, axis=1)
                        mtime = np.append(mtime, at)
                        mfcycle = np.append(mfcycle, fcycle)

                    del ahs, atm, atp, adm, adp, at, fcycle

            print(" Read WW3 data OK.")
            print('  ')

        else:
            sys.exit(' Point output file format not recognized: only bull, bull_tar, and .nc implemented.')
            # include other text formats: tab50, .ts

        print(" Start building the matchups model/buoy ...")
        print('  ')



# BUOYS
bwind = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
bhs = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
btm = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
btp = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
bdm = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
bdp = np.zeros((np.size(stname), np.size(mtime)), 'f') * np.nan
lat = np.zeros(np.size(stname), 'f') * np.nan
lon = np.zeros(np.size(stname), 'f') * np.nan

# Help reading NDBC buoys, divided by year
yrange = np.array(np.arange(time.gmtime(mtime.min())[0], time.gmtime(mtime.min())[0] + 1, 1)).astype('int')

# Loop buoys
for b in range(0, np.size(stname)):
    ahs = []
    try:
        awm = []
        ahs = []
        atm = []
        atp = []
        adm = []
        atime = []
        for y in yrange:
            f = nc.Dataset(ndbcp + "/" + stname[b] + "h" + repr(y) + ".nc")
            if 'wave_height' in f.variables.keys():
                ahs = np.append(ahs, f.variables['wave_height'][:, 0, 0])
            elif 'hs' in f.variables.keys():
                ahs = np.append(ahs, f.variables['hs'][:, 0, 0])
            elif 'swh' in f.variables.keys():
                ahs = np.append(ahs, f.variables['swh'][:, 0, 0])

            if 'wind_spd' in f.variables.keys():
                awm = np.append(awm, f.variables['wind_spd'][:, 0, 0])
            else:
                awm = np.array(np.copy(ahs * np.nan))

            if 'average_wpd' in f.variables.keys():
                atm = np.append(atm, f.variables['average_wpd'][:, 0, 0])
            else:
                atm = np.array(np.copy(ahs * np.nan))

            if 'dominant_wpd' in f.variables.keys():
                atp = np.append(atp, f.variables['dominant_wpd'][:, 0, 0])
            else:
                atp = np.array(np.copy(ahs * np.nan))

            if 'mean_wave_dir' in f.variables.keys():
                adm = np.append(adm, f.variables['mean_wave_dir'][:, 0, 0])
            else:
                adm = np.array(np.copy(ahs * np.nan))

            if 'latitude' in f.variables.keys():
                lat[b] = f.variables['latitude'][:]
            elif 'LATITUDE' in f.variables.keys():
                lat[b] = f.variables['LATITUDE'][:]
            else:
                lat[b] = np.nan

            if 'longitude' in f.variables.keys():
                lon[b] = f.variables['longitude'][:]
            elif 'LONGITUDE' in f.variables.keys():
                lon[b] = f.variables['LONGITUDE'][:]
            else:
                lon[b] = np.nan

            atime = np.append(atime, np.array(f.variables['time'][:]).astype('double'))

            f.close()
            del f

        adp = adm * np.nan  # no peak direction available in this format

        if np.size(ahs) > 0:
            # First layer of simple quality-control
            indq = np.where((ahs > 30.) | (ahs < 0.0))
            if np.size(indq) > 0:
                ahs[indq] = np.nan
                del indq

            indq = np.where((atm > 40.) | (atm < 0.0))
            if np.size(indq) > 0:
                atm[indq] = np.nan
                del indq

            indq = np.where((atp > 40.) | (atp < 0.0))
            if np.size(indq) > 0:
                atp[indq] = np.nan
                del indq

            indq = np.where((adm > 360.) | (adm < -180.))
            if np.size(indq) > 0:
                adm[indq] = np.nan
                del indq

            indq = np.where((adp > 360.) | (adp < -180.))
            if np.size(indq) > 0:
                adp[indq] = np.nan
                del indq

            indq = np.where((awm > 50.) | (awm < 0.0))
            if np.size(indq) > 0:
                awm[indq] = np.nan
                del indq

            c = 0
            for t in mtime:
                indt = np.where(np.abs(atime - t) < 1800.)[0]
                if np.size(indt) > 0:
                    if np.any(ahs[indt].mask == False):
                        bhs[b, c] = np.nanmean(ahs[indt][ahs[indt].mask == False])
                    if np.any(atm[indt].mask == False):
                        btm[b, c] = np.nanmean(atm[indt][atm[indt].mask == False])
                    if np.any(atp[indt].mask == False):
                        btp[b, c] = np.nanmean(atp[indt][atp[indt].mask == False])
                    if np.any(adm[indt].mask == False):
                        bdm[b, c] = np.nanmean(adm[indt][adm[indt].mask == False])
                    if np.any(adp[indt].mask == False):
                        bdp[b, c] = np.nanmean(adp[indt][adp[indt].mask == False])
                    if np.any(awm[indt].mask == False):
                        bwind[b, c] = np.nanmean(awm[indt][awm[indt].mask == False])
                c += 1

        print("   station " + stname[b] + "  ok")

    except Exception as e:
        print("Error occurred while processing station", stname[b])
        print(e)

# Simple quality-control (range)
ind = np.where((bhs > 30.) | (bhs < 0.0))
if np.size(ind) > 0:
    bhs[ind] = np.nan
    del ind

ind = np.where((btm > 40.) | (btm < 0.0))
if np.size(ind) > 0:
    btm[ind] = np.nan
    del ind

ind = np.where((btp > 40.) | (btp < 0.0))
if np.size(ind) > 0:
    btp[ind] = np.nan
    del ind

ind = np.where((bdm > 360.) | (bdm < -180.))
if np.size(ind) > 0:
    bdm[ind] = np.nan
    del ind

ind = np.where((bdp > 360.) | (bdp < -180.))
if np.size(ind) > 0:
    bdp[ind] = np.nan
    del ind

ind = np.where((bwind > 50.0) | (bwind < 0.0))
if np.size(ind) > 0:
    bwind[ind] = np.nan
    del ind

ind = np.where((mhs > 30.) | (mhs < 0.0))
if np.size(ind) > 0:
    mhs[ind] = np.nan
    del ind

ind = np.where((mtm > 40.) | (mtm < 0.0))
if np.size(ind) > 0:
    mtm[ind] = np.nan
    del ind

ind = np.where((mtp > 40.) | (mtp < 0.0))
if np.size(ind) > 0:
    mtp[ind] = np.nan
    del ind

ind = np.where((mdm > 360.) | (mdm < -180.))
if np.size(ind) > 0:
    mdm[ind] = np.nan
    del ind

ind = np.where((mdp > 360.) | (mdp < -180.))
if np.size(ind) > 0:
    mdp[ind] = np.nan
    del ind

ind = np.where((mwn > 50.) | (mwn < 0.0))
if np.size(ind) > 0:
    mwn[ind] = np.nan
    del ind

# Clean data excluding some stations. Select matchups only when model and buoy are available.
ind = np.where((np.isnan(lat) == False) & (np.isnan(lon) == False) & (np.isnan(np.nanmean(mhs, axis=1)) == False) & (np.isnan(np.nanmean(bhs, axis=1)) == False))
if np.size(ind) > 0:
    stname = np.array(stname[ind[0]])
    lat = np.array(lat[ind[0]])
    lon = np.array(lon[ind[0]])
    mhs = np.array(mhs[ind[0], :])
    mtm = np.array(mtm[ind[0], :])
    mtp = np.array(mtp[ind[0], :])
    mdm = np.array(mdm[ind[0], :])
    mdp = np.array(mdp[ind[0], :])
    mwn = np.array(mwn[ind[0], :])
    bhs = np.array(bhs[ind[0], :])
    btm = np.array(btm[ind[0], :])
    btp = np.array(btp[ind[0], :])
    bdm = np.array(bdm[ind[0], :])
    bdp = np.array(bdp[ind[0], :])
    bwind = np.array(bwind[ind[0], :])
else:
    sys.exit(' Error: No matchups Model/Buoy available.')

print(" Matchups model/buoy complete. Total of " + repr(np.size(ind)) + " stations/buoys available.")
del ind

# Processing grid and/or cyclone information
if gridinfo:
    print(" Adding extra information ... ")
    alon = np.copy(lon)
    alon[alon < 0] = alon[alon < 0] + 360.
    indgplat = []
    indgplon = []
    for i in range(0, lat.shape[0]):
        # indexes nearest point.
        indgplat = np.append(indgplat, np.where(abs(mlat - lat[i]) == abs(mlat - lat[i]).min())[0][0])
        indgplon = np.append(indgplon, np.where(abs(mlon - alon[i]) == abs(mlon - alon[i]).min())[0][0])

    indgplat = np.array(indgplat).astype('int')
    indgplon = np.array(indgplon).astype('int')
    pdistcoast = np.zeros(lat.shape[0], 'f') * np.nan
    pdepth = np.zeros(lat.shape[0], 'f') * np.nan
    poni = np.zeros(lat.shape[0], 'f') * np.nan
    phsmz = np.zeros(lat.shape[0], 'f') * np.nan
    for i in range(0, lat.shape[0]):
        pdistcoast[i] = distcoast[indgplat[i], indgplon[i]]
        pdepth[i] = depth[indgplat[i], indgplon[i]]
        poni[i] = oni[indgplat[i], indgplon[i]]
        phsmz[i] = hsmz[indgplat[i], indgplon[i]]

    print(" Grid Information Included.")

    # Excluding shallow water points too close to the coast (mask information not accurate)
    ind = np.where((np.isnan(pdistcoast) == False) & (np.isnan(pdepth) == False))
    if np.size(ind) > 0:
        stname = np.array(stname[ind[0]])
        lat = np.array(lat[ind[0]])
        lon = np.array(lon[ind[0]])
        mhs = np.array(mhs[ind[0], :])
        mtm = np.array(mtm[ind[0], :])
        mtp = np.array(mtp[ind[0], :])
        mdm = np.array(mdm[ind[0], :])
        mdp = np.array(mdp[ind[0], :])
        bhs = np.array(bhs[ind[0], :])
        btm = np.array(btm[ind[0], :])
        btp = np.array(btp[ind[0], :])
        bdm = np.array(bdm[ind[0], :])
        bdp = np.array(bdp[ind[0], :])
        pdistcoast = np.array(pdistcoast[ind[0]])
        pdepth = np.array(pdepth[ind[0]])
        poni = np.array(poni[ind[0]])
        phsmz = np.array(phsmz[ind[0]])
    else:
        sys.exit(' Error: No matchups Model/Buoy available after using grid mask.')

    del ind

    if cyclonemap:
        fcmap = np.zeros((lat.shape[0], mtime.shape[0]), 'f') * np.nan
        for t in range(0, np.size(mtime)):
            # search for cyclone time index and cyclone map
            indt = np.where(np.abs(ctime - mtime[t]) < 5400.)
            if np.size(indt) > 0:
                for i in range(0, lat.shape[0]):
                    fcmap[i, t] = np.array(cmap[indt[0][0], indgplat[i], indgplon[i]])

                del indt
            else:
                print('     - No cyclone information for this time step: ' + repr(t))

        ind = np.where(fcmap < 0)
        if np.size(ind) > 0:
            fcmap[ind] = np.nan

        print(" Cyclone Information Included.")

# Edit format if this is forecast model data. Reshape and allocate
if forecastds > 0:
    unt = np.unique(mfcycle)
    mxsz = 1

    for i in range(0, unt.shape[0]):
        ind = np.where(mfcycle == unt[i])[0]
        mxsz = np.max([mxsz, np.size(ind)])

    for i in range(0, unt.shape[0]):
        ind = np.where(mfcycle == unt[i])[0]
        if i == 0:
            nmhs = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmtm = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmtp = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmdm = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmdp = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmwn = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbhs = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbtm = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbtp = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbdm = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbdp = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nbwind = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan
            nmtime = np.zeros((unt.shape[0], mxsz), 'double') * np.nan
            if cyclonemap:
                nfcmap = np.zeros((mhs.shape[0], unt.shape[0], mxsz), 'f') * np.nan

        nmtime[i, 0:np.size(ind)] = np.array(mtime[ind]).astype('double')
        nmhs[:, i, :][:, 0:np.size(ind)] = np.array(mhs[:, ind])
        nmtm[:, i, :][:, 0:np.size(ind)] = np.array(mtm[:, ind])
        nmtp[:, i, :][:, 0:np.size(ind)] = np.array(mtp[:, ind])
        nmdm[:, i, :][:, 0:np.size(ind)] = np.array(mdm[:, ind])
        nmdp[:, i, :][:, 0:np.size(ind)] = np.array(mdp[:, ind])
        nmwn[:, i, :][:, 0:np.size(ind)] = np.array(mwn[:, ind])
        nbhs[:, i, :][:, 0:np.size(ind)] = np.array(bhs[:, ind])
        nbtm[:, i, :][:, 0:np.size(ind)] = np.array(btm[:, ind])
        nbtp[:, i, :][:, 0:np.size(ind)] = np.array(btp[:, ind])
        nbdm[:, i, :][:, 0:np.size(ind)] = np.array(bdm[:, ind])
        nbdp[:, i, :][:, 0:np.size(ind)] = np.array(bdp[:, ind])
        nbwind[:, i, :][:, 0:np.size(ind)] = np.array(bwind[:, ind])
        if cyclonemap:
            nfcmap[:, i, :][:, 0:np.size(ind)] = np.array(fcmap[:, ind])

    ind = np.where((nmhs > 0.0) & (nbhs > 0.0))

else:
    ind = np.where((mhs > 0.0) & (bhs > 0.0))

if np.size(ind) > 0:
    print(' Total amount of matchups model/buoy: ' + repr(np.size(ind)))

    # Save netcdf output file
    lon[lon > 180.] = lon[lon > 180.] - 360.
    initime = str(time.gmtime(mtime.min())[0]) + str(time.gmtime(mtime.min())[1]).zfill(2) + str(time.gmtime(mtime.min())[2]).zfill(2) + str(time.gmtime(mtime.min())[3]).zfill(2)
    fintime = str(time.gmtime(mtime.max())[0]) + str(time.gmtime(mtime.max())[1]).zfill(2) + str(time.gmtime(mtime.max())[2]).zfill(2) + str(time.gmtime(mtime.max())[3]).zfill(2)

    # Ensure model_name is defined
    if 'model_name' not in locals():
        model_name = ''

    ncfile = nc.Dataset(f'WW3.{model_name}Buoy{ftag}_{initime}to{fintime}.nc', "w", format=fnetcdf)
    print(f"Model Name: {model_name}, Tag: {ftag}, Start Time: {initime}, End Time: {fintime}")
    ncfile.history = "Matchups of WAVEWATCHIII point output (table) and NDBC and Copernicus Buoys. Total of " + repr(bhs[bhs > 0.].shape[0]) + " observations or pairs model/observation."
    ncfile.initial_condition = initime
    ncfile.time_units = "seconds since 1970-01-01T00:00:00+00:00"

    # Create dimensions
    ncfile.createDimension('buoypoints', bhs.shape[0])
    if gridinfo:
        ncfile.createDimension('GlobalOceansSeas', ocnames.shape[0])
        ncfile.createDimension('HighSeasMarineZones', hsmznames.shape[0])
    if cyclonemap:
        ncfile.createDimension('cycloneinfo', cinfo.shape[0])
        vcinfo = ncfile.createVariable('cycloneinfo', 'S1', ('cycloneinfo'))

    # Create variables
    vstname = ncfile.createVariable('buoyID', 'S1', ('buoypoints'))
    vlat = ncfile.createVariable('latitude', 'f4', ('buoypoints'))
    vlon = ncfile.createVariable('longitude', 'f4', ('buoypoints'))

    if forecastds > 0:
        ncfile.createDimension('time', nmhs.shape[2])
        ncfile.createDimension('fcycle', unt.shape[0])
        vt = ncfile.createVariable('time', 'f8', ('fcycle', 'time'))
        vmhs = ncfile.createVariable('model_hs', 'f4', ('buoypoints', 'fcycle', 'time'))
        vmtm = ncfile.createVariable('model_tm', 'f4', ('buoypoints', 'fcycle', 'time'))
        vmtp = ncfile.createVariable('model_tp', 'f4', ('buoypoints', 'fcycle', 'time'))
        vmdm = ncfile.createVariable('model_dm', 'f4', ('buoypoints', 'fcycle', 'time'))
        vmdp = ncfile.createVariable('model_dp', 'f4', ('buoypoints', 'fcycle', 'time'))
        vmwn = ncfile.createVariable('model_wind', 'f4', ('buoypoints', 'fcycle', 'time'))

        vbhs = ncfile.createVariable('obs_hs', 'f4', ('buoypoints', 'fcycle', 'time'))
        vbtm = ncfile.createVariable('obs_tm', 'f4', ('buoypoints', 'fcycle', 'time'))
        vbtp = ncfile.createVariable('obs_tp', 'f4', ('buoypoints', 'fcycle', 'time'))
        vbdm = ncfile.createVariable('obs_dm', 'f4', ('buoypoints', 'fcycle', 'time'))
        vbdp = ncfile.createVariable('obs_dp', 'f4', ('buoypoints', 'fcycle', 'time'))
        vbwind = ncfile.createVariable('obs_wind', 'f4', ('buoypoints', 'fcycle', 'time'))

    else:
        ncfile.createDimension('time', bhs.shape[1])
        vt = ncfile.createVariable('time', 'f8', ('time'))
        vmhs = ncfile.createVariable('model_hs', 'f4', ('buoypoints', 'time'))
        vmtm = ncfile.createVariable('model_tm', 'f4', ('buoypoints', 'time'))
        vmtp = ncfile.createVariable('model_tp', 'f4', ('buoypoints', 'time'))
        vmdm = ncfile.createVariable('model_dm', 'f4', ('buoypoints', 'time'))
        vmdp = ncfile.createVariable('model_dp', 'f4', ('buoypoints', 'time'))
        vmwn = ncfile.createVariable('model_wind', 'f4', ('buoypoints', 'time'))

        vbhs = ncfile.createVariable('obs_hs', 'f4', ('buoypoints', 'time'))
        vbtm = ncfile.createVariable('obs_tm', 'f4', ('buoypoints', 'time'))
        vbtp = ncfile.createVariable('obs_tp', 'f4', ('buoypoints', 'time'))
        vbdm = ncfile.createVariable('obs_dm', 'f4', ('buoypoints', 'time'))
        vbdp = ncfile.createVariable('obs_dp', 'f4', ('buoypoints', 'time'))
        vbwind = ncfile.createVariable('obs_wind', 'f4', ('buoypoints', 'time'))

    if gridinfo:
        vpdistcoast = ncfile.createVariable('distcoast', 'f4', ('buoypoints'))
        vpdepth = ncfile.createVariable('depth', 'f4', ('buoypoints'))
        vponi = ncfile.createVariable('GlobalOceansSeas', 'f4', ('buoypoints'))
        vocnames = ncfile.createVariable('names_GlobalOceansSeas', 'S1', ('GlobalOceansSeas'))
        vphsmz = ncfile.createVariable('HighSeasMarineZones', 'f4', ('buoypoints'))
        vhsmznames = ncfile.createVariable('names_HighSeasMarineZones', 'S1', ('HighSeasMarineZones'))
    if cyclonemap:
        if forecastds > 0:
            vcmap = ncfile.createVariable('cyclone', 'f4', ('buoypoints', 'fcycle', 'time'))
        else:
            vcmap = ncfile.createVariable('cyclone', 'f4', ('buoypoints', 'time'))

    # Assign units
    vlat.units = 'degrees_north'
    vlon.units = 'degrees_east'
    vt.units = 'seconds since 1970-01-01T00:00:00+00:00'
    vmhs.units = 'm'
    vbhs.units = 'm'
    vmtm.units = 's'
    vbtm.units = 's'
    vmtp.units = 's'
    vbtp.units = 's'
    vmdm.units = 'degrees'
    vbdm.units = 'degrees'
    vmdp.units = 'degrees'
    vbdp.units = 'degrees'
    vmwn.unit = 'm/s'
    vbwind.unit = 'm/s'

    if gridinfo:
        vpdepth.units = 'm'
        vpdistcoast.units = 'km'

    # Allocate Data
    vstname[:] = stname[:]
    vlat[:] = lat[:]
    vlon[:] = lon[:]
    initime_unix = timegm(strptime(initime, '%Y%m%d%H'))

    if forecastds > 0:
        vt[:, :] = nmtime[:, :]
        vmhs[:, :, :] = nmhs[:, :, :]
        vmtm[:, :, :] = nmtm[:, :, :]
        vmtp[:, :, :] = nmtp[:, :, :]
        vmdm[:, :, :] = nmdm[:, :, :]
        vmdp[:, :, :] = nmdp[:, :, :]
        vmwn[:, :, :] = nmwn[:, :, :]
        vbhs[:, :, :] = nbhs[:, :, :]
        vbtm[:, :, :] = nbtm[:, :, :]
        vbtp[:, :, :] = nbtp[:, :, :]
        vbdm[:, :, :] = nbdm[:, :, :]
        vbdp[:, :, :] = nbdp[:, :, :]
        vbwind[:, :, :] = nbwind[:, :, :]

    if gridinfo:
        vpdistcoast[:] = pdistcoast[:]
        vpdepth[:] = pdepth[:]
        vponi[:] = poni[:]
        vocnames[:] = ocnames[:]
        vphsmz[:] = phsmz[:]
        vhsmznames[:] = hsmznames[:]
    if cyclonemap:
        vcinfo[:] = cinfo[:]
        if forecastds > 0:
            vcmap[:, :, :] = nfcmap[:, :, :]
        else:
            vcmap[:, :] = fcmap[:, :]

    fcst_hr = np.full_like(mtime, np.nan, dtype='float64')
    for i in range(mtime.shape[0]):
        if mtime.ndim > 1:
            for j in range(mtime.shape[1]):
                if not np.isnan(mtime[i, j]):
                    fcst_hr[i, j] = (mtime[i, j] - initime_unix) / 3600
        else:
            if not np.isnan(mtime[i]):
                fcst_hr[i] = (mtime[i] - initime_unix) / 3600

    # Add fcst_hr
    vfcst_hr = ncfile.createVariable('fcst_hr', 'f8', ('buoypoints', 'time'))
    vfcst_hr.units = 'hours'
    vfcst_hr[:] = fcst_hr

    ncfile.close()
    print(' ')
    print(f'Done. Netcdf ok. New file saved: WW3.{model_name}_Buoy{ftag}_{initime}to{fintime}.nc')

    # File deletion section
    files_to_delete = [
        os.path.join(output_dir, '*_contents.txt'),
        os.path.join(output_dir, '*_id.txt'),
        os.path.join(output_dir, '*.spec_tar')
    ]

    for pattern in files_to_delete:
        for file in glob.glob(pattern):
            try:
                os.remove(file)
                print(f'Deleted file: {file}')
            except OSError as e:
                print(f'Error deleting file {file}: {e}')

    # Folder deletion section
    try:
        shutil.rmtree(extracted_folder)
        print(f'Deleted folder: {extracted_folder}')
    except OSError as e:
        print(f'Error deleting folder {extracted_folder}: {e}')

    print('Temporary files and folder deleted.')

