#!/bin/bash
#SBATCH --job-name=jigsaw_py_RWPSng     # Job name
#SBATCH --mail-type=END             # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=keston.smith@noaa.gov  # Where to send mail
#SBATCH --mem-per-cpu=256000mb         # Memory per processor
#SBATCH --time=08:00:00             # Time limit hrs:min:sec
#SBATCH --output=mpi_test_%j.log    # Standard output/error
##SBATCH --exclusive=user
#SBATCH --error=%j.err
##SBATCH --partition=marine-cpu
#SBATCH --account=marine-cpu
#SBATCH --nodes=1



module purge
source /scratch3/NCEPDEV/climate/Keston.Smith/UrsaMeshgenEnv3/jigsawenv/bin/activate
pip list -v

##python3 RWPSMeshGenScript.GSHHSpy > NonGlobalMeshGen.HSHHS.out
##python3 RWPSMeshGenScript.GSHHS.py >  RWPSMeshGenScript.GSHHS.out
python3 MeshGenScript.NWcoastal.py > MeshGenScript.NWcoastal.out
