#!/bin/bash
#SBATCH --job-name=jigsaw_py     # Job name
#SBATCH --mem-per-cpu=256000mb         # Memory per processor
#SBATCH --time=08:00:00             # Time limit hrs:min:sec
#SBATCH --output=MeshGen_%j.log    # Standard output/error
#SBATCH --error=%j.err
#SBATCH --account=marine-cpu
#SBATCH --nodes=1



module purge
source /scratch3/NCEPDEV/climate/Keston.Smith/UrsaMeshgenEnv3/jigsawenv/bin/activate
pip list -v

python3 MeshGenScript.NWcoastal.py > MeshGenScript.NWcoastal.out
# python3 RWPSMeshGenScript.GSSHSxOSM.NewOrleans.py >RWPSMeshGenScript.GSSHSxOSM.NewOrleans.out
# python3 RWPSMeshGenScript.GSSHS.py >RWPSMeshGenScript.GSSHS.out
